### ISSUE TITLE
Chinese metalanguage for creating a GB doc

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#36]
One requirement for using this in GB is that the metalanguage is in Chinese.

e.g.,
```
draft
vs
稿
```

Makes me thing whether Selagraph is a better choice than Asciidoc for this...

**Comment by opoudjis** [comment]
Inasmuch as Selagraph does not exist yet, no.

Since you're using asciidoctor-iso to create Chinese documents, the metalanguage issue has to be confronted in asciidoctor-iso and, more importantly, isodoc. (In fact the metalanguage can stay English in asciidoctor-iso: it's the output from isodoc that matters.) https://github.com/riboseinc/isodoc/issues/47

**Comment by opoudjis** [comment]
Now done in https://github.com/riboseinc/isodoc/issues/47
