### ISSUE TITLE
Apply TCS GB Stylesheet to generated word doc

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#37]
With style names translated.
[tcs-stylesheet.html.zip](https://github.com/riboseinc/asciidoctor-gb/files/1779932/tcs-stylesheet.html.zip)

**Comment by opoudjis** [comment]
Done:

* Headings, Note, Examples, paras

To do:

* Coverpage styles. (I won't do much here, because they are so manual and fiddly, and I spent a lot of time on existing exemplar).
* Lists (will also need to adjust ISO stylesheet)

There's a lot of lists in the CSS that I'm hoping I can pass by, because they do autonumbering that's already taken care of by Asciidoc.

**Comment by opoudjis** [comment]
Done lists, thanks to https://github.com/riboseinc/html2doc/issues/12. (This means I can now make lists have "1), a)" numbering in ISO as well—except that the ISO template does not style lists that way.)

Footnotes in theory should have "1)" styling as well. In practice, that seems to be ignored by Word on autogeneration; even worse, when I add a new footnote to the document, Word puts both the bracketed reference and the superscript reference. My current inclination is to leave this as too hard.

**Comment by opoudjis** [comment]
The cover page styles were preserved accurately in the document I took them from.

I believe I have replicated the stylesheet as much as is reasonable to.
