### ISSUE TITLE
Cover page styling: ICS code and CCS code formatting

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#62]
1. ICS code numbers should be in SimHei.
1. CCS code category should be separated from code number with one ASCII space.
1. CCS code category and code number should both be in SimHei.

Now:
<img width="179" alt="screen shot 2018-04-03 at 8 41 58 am" src="https://user-images.githubusercontent.com/11865/38221661-b201467e-371b-11e8-95ad-3816921b7b25.png">

Original:
<img width="183" alt="screen shot 2018-04-03 at 8 42 06 am" src="https://user-images.githubusercontent.com/11865/38221677-c55a82e4-371b-11e8-892c-227fd2a2181f.png">

**Comment by opoudjis** [comment]
In addition, letters should be in boldface.

**Comment by opoudjis** [comment]
Actually, the boldface and ICS styling varies from document to document. GB/T 19018-2017 (which I understand to be the most authoritative)  has the following, and that's what I'll abide by. Note that its CCS code category is NOT in SimHei; you're seeing SimHei because the document you're looking at is using Word fields (hence the grey). GB_T 19488.2, which doesn't use Word fields, has NO SimHei.

<img width="152" alt="ics" src="https://user-images.githubusercontent.com/1911039/38232469-82d74e5e-375a-11e8-8e30-e35c15138a7a.png">

**Comment by opoudjis** [comment]
The real issue here is that GB/T 1.1 is simply not being complied with by anyone. If we're going to abide by https://github.com/riboseinc/asciidoctor-gb/issues/56 , that is just SimHei for the whole field, including "ICS".

**Comment by ronaldtse** [comment]
By now we should also realize that the "SimHei" font is just Apple's rendition of the "Simplified Hei" ("sans serif for simplified characters"); "SimSun" is Apple's rendition of the "Simplified Sung" ("serif for simplified characters"). My table was being too simplistic in description.
