### ISSUE TITLE
Cover page layout: Issue and Implementation dates styling

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#63]
1. These dates should be in SimHei not Roman
2. The dash between the dates seem special (it's a SimHei dash but has some extra spacing on both sides)

Current:
<img width="844" alt="screen shot 2018-04-03 at 9 04 57 am" src="https://user-images.githubusercontent.com/11865/38222196-50bff9de-371e-11e8-8731-5df7d5df0202.png">

Original:
<img width="839" alt="screen shot 2018-04-03 at 9 04 03 am" src="https://user-images.githubusercontent.com/11865/38222186-494a6586-371e-11e8-8431-11778087dadc.png">

**Comment by opoudjis** [comment]
You're jumping the gun. :-) This is an English-language spec. If this was in Chinese, it would all be in SimHei. The real question is, how much of the coverpage will be in SimHei/SimSun, if the spec is in English.

**Comment by opoudjis** [comment]
The dash is possibly an en-dash, or possibly just a fixed-width SimHei hyphen; I'll find out.

**Comment by ronaldtse** [comment]
In any case these apply:
1. the font for the date should be the Sans Serif font
2. a space between the date and the Chinese word 
3. a space between the dash and each date element (maybe)
😉

**Comment by opoudjis** [comment]
I'm actually not convinced at all there is a space between the date and the Chinese word in the instance you give, given how ugly SimHei Roman is. Much more to the point, there is no space either between dates and Chinese, or date elements and dashes, in the Word document for GB/T 19488.2-2008 (and it's using simple hyphens), which we are treating as authoritative; and I'm very reluctant to take SDMX seriously, given that it uses fields which may be disrupting rendering. GB/T 1.1 is silent on the issue—and since Chinese wouldn't normally be inserting spaces after dates, its silence indicates that the default for Chinese should be assumed here: that there is no space I think this is simply the tragedy of how Roman characters are rendered in Chinese fonts. 

So in fact, I'm not fixing this. I've already switched the Roman "headerfont" to Calibri, so this will now be rendering as Sans-Serif for both English and Chinese texts.

**Comment by ronaldtse** [comment]
I’d like to reiterate that the authoritative page we need to match against is the cover page of GB/T 19108, so space or not it doesn’t matter that much, as long as there is “horizontal spacing” between the date elements and the dashes. 

Also, the dates should be using SimHei which is also identical to the one the 发布/实施 characters after them. 

This is should still an issue because it used to work properly?

**Comment by ronaldtse** [comment]
@opoudjis FYI I've uploaded the cover page of GB/T 19018 here for reference.

**Comment by opoudjis** [comment]
All I'm seeing is an Ascii space between the date and the "published/activated"; inserted. Enforced Header Font.

**Comment by ronaldtse** [comment]
@opoudjis yes you're right. Thanks.
