### ISSUE TITLE
Integrate cover page from gbdoc-style

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#93]
As described here: https://github.com/riboseinc/gbdoc-style/issues/9

**Comment by opoudjis** [comment]
Pierre's two stylesheets merged. To do: 

* create a compliance mode for HTML output
* create the title page elements that are required for the compliance stylesheet. Unless you tell me otherwise, @ronaldtse, I will add those elements to both Compliance and Human html, so I can continue to generate just the one HTML document with two styles.

**Comment by opoudjis** [comment]
I've done it, but I don't think what I'm coming up with is really conformant to the dimensions specified in GB/T1.1. I'm bouncing this back to Pierre.

**Comment by ronaldtse** [comment]
Agree with @opoudjis on using shared elements and also that the compliance style needs more work from @pierrefortier .

Thanks for updating the stylesheets; at least we have normal looking output for now.

**Comment by opoudjis** [comment]
I ended up making a distinct front page and copy pasting from Pierre's exemplar; I may or may not restore any missing elements to the human coverpage later. 

Checked in. @ronaldtse, please review.

[html.zip](https://github.com/riboseinc/asciidoctor-gb/files/2239333/html.zip)

**Comment by opoudjis** [comment]
I'm wondering if it wouldn't be simpler to make the compliant front page the front page for the non compliant HTML, without the vertical space constraint.

**Comment by opoudjis** [comment]
I've done so, and I'm satisfied with the results:

[rice.html 2.zip](https://github.com/riboseinc/asciidoctor-gb/files/2243230/rice.html.2.zip)
